controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_words_game: 
    path: '/api/words-game'
    controller: App\Controller\WordsGameController::game
    methods: [GET]


